name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint pytest
      timeout-minutes: 5
    
    - name: Run linting
      run: |
        pylint src/*.py
      timeout-minutes: 5
    
    - name: Run tests
      run: |
        pytest src
      timeout-minutes: 10

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: pytest-results.xml
      # This step runs even if the previous step fails
      if: always()
      timeout-minutes: 2  # Timeout for uploading results
